stages:
  - build
  - test

variables:
  IMAGE: $CI_REGISTRY_IMAGE
  TEST_TAG: "test-$CI_COMMIT_SHORT_SHA"
  TEST_LATEST: "test"
  PROD_TAG: "main-$CI_COMMIT_SHORT_SHA"
  PROD_LATEST: "latest"

workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /-nodeployment$/
      when: never
    - when: always

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

.build_app:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - >
      printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}'
      "$CI_REGISTRY" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD"
      > /kaniko/.docker/config.json
    - '[ -n "$SITE_URL" ] || { echo "ERROR: SITE_URL not set"; exit 1; }'
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg SITE_URL="$SITE_URL"
      --destination "$IMAGE:$DEST1"
      ${DEST2:+--destination "$IMAGE:$DEST2"}
      --cache=false
      # no cache - only this line active:
      #      --cache=false
      # with cache - both lines active:
      #      --cache=true
      #      --cache-repo "$IMAGE/cache"

# TEST
build_test:
  extends: .build_app
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
  variables:
    SITE_URL: https://histvv-2025.t01.cs.zi.uzh.ch
    DEST1: "$TEST_TAG"
    DEST2: "$TEST_LATEST"

# MAIN
build_prod:
  extends: .build_app
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    # SITE_URL is used for the link in the header section of the website.
    SITE_URL: https://histvv.uzh.ch
    #SITE_URL: https://histvv-2025.p01.cs.zi.uzh.ch
    DEST1: "$PROD_TAG"
    DEST2: "$PROD_LATEST"

# Deactivate the default template job, but keep it available for "extends"
container_scanning:
  rules:
    - when: never

# Scan TEST
scan_test:
  extends: container_scanning
  stage: test
  needs: ["build_test"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
  variables:
    GIT_STRATEGY: none
    CS_IMAGE: "$IMAGE:$TEST_LATEST"
    CS_REGISTRY: "$CI_REGISTRY"
    CS_REGISTRY_USER: "$CI_REGISTRY_USER"
    CS_REGISTRY_PASSWORD: "$CI_JOB_TOKEN"

# Scan MAIN
scan_prod:
  extends: container_scanning
  stage: test
  needs: ["build_prod"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    GIT_STRATEGY: none
    CS_IMAGE: "$IMAGE:$PROD_LATEST"
    CS_REGISTRY: "$CI_REGISTRY"
    CS_REGISTRY_USER: "$CI_REGISTRY_USER"
    CS_REGISTRY_PASSWORD: "$CI_JOB_TOKEN"
