stages:
  - build
  - test

variables:
  SITE_URL: "https://histvv-2025.t01.cs.zi.uzh.ch"
  IMAGE: $CI_REGISTRY_IMAGE
  TAG_COMMIT: $CI_COMMIT_SHORT_SHA
  IMG_COMMIT: $IMAGE:$TAG_COMMIT

workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /-nodeployment$/
      when: never
    - when: always

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

build_and_push:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - |
      EXTRA_DEST=""
      if [ -n "$CI_COMMIT_TAG" ]; then
        EXTRA_DEST="--destination $IMAGE:$CI_COMMIT_TAG"
      fi

      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
        --build-arg SITE_URL="$SITE_URL" \
        --destination "$IMG_COMMIT" \
        --destination "$IMAGE:$CI_COMMIT_REF_NAME" \
        $EXTRA_DEST
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

container_scanning:
  stage: test
  needs: ["build_and_push"]
  variables:
    CS_IMAGE: $IMG_COMMIT
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

