stages:
  - build
  - test

variables:
  IMAGE: $CI_REGISTRY_IMAGE
  TAG_COMMIT: $CI_COMMIT_SHORT_SHA
  IMG_COMMIT: $IMAGE:$TAG_COMMIT

workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /-nodeployment$/
      when: never
    - when: always

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

# ===== Test-Image =====
build_test:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
  script: |
    set -euo pipefail
    SITE_URL="https://histvv-2025.t01.cs.zi.uzh.ch"
    [ -n "$SITE_URL" ] || { echo "SITE_URL is empty"; exit 1; }

    /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
      --build-arg SITE_URL="$SITE_URL" \
      --destination "$IMG_COMMIT"

# ===== Prod-Image =====
build_prod:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script: |
    set -euo pipefail
    SITE_URL="https://histvv-2025.p01.cs.zi.uzh.ch"
    [ -n "$SITE_URL" ] || { echo "SITE_URL is empty"; exit 1; }

    /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
      --build-arg SITE_URL="$SITE_URL" \
      --destination "$IMG_COMMIT"


container_scanning:
  stage: test
  needs: ["build_prod", "build_test"]
  variables:
    CS_IMAGE: $IMG_COMMIT   # scanne exakt das Commit-Image
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "test"' 
