stages:
  - build-and-push

variables:
  SITE_URL: "https://histvv-2025.t01.cs.zi.uzh.ch"
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /-nodeployment$/
      when: never
    - when: always

build_and_push:
  stage: build-and-push
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg SITE_URL=$SITE_URL
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination $TAG_COMMIT
      --destination $TAG_LATEST

#stages:
#  - build
#
#variables:
#  SITE_URL: "https://histvv-2025.t01.cs.zi.uzh.ch"
#  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
#  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
#
#workflow:
#  rules:
#    - if: $CI_COMMIT_TITLE =~ /-nodeployment$/
#      when: never
#    - when: always
#
#docker-build:
#  stage: build
#  image: docker:stable
#  services:
#    - docker:dind
#  script:
#    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
#    - docker build --build-arg SITE_URL=$SITE_URL -t $TAG_COMMIT -t $TAG_LATEST .
#    - docker push $TAG_COMMIT
#    - docker push $TAG_LATEST
#  only:
#    - main
