stages:
  - build-and-push
  - test

variables:
  SITE_URL: "https://histvv-2025.t01.cs.zi.uzh.ch"
  TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  TAG_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  TAG_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

workflow:
  rules:
    - if: $CI_COMMIT_TITLE =~ /-nodeployment$/
      when: never
    - when: always

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

container_scanning:
  stage: test
  needs: ["build_and_push"]
  variables:
    CS_IMAGE: $TAG_LATEST

build_and_push:
  stage: build-and-push
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg SITE_URL=$SITE_URL
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination $TAG_COMMIT
      --destination $TAG_BRANCH
      --destination $TAG_LATEST

