services:
  dev:
    init: true
    container_name: histvv2025-dev
    build:
      context: .
      target: builder
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - NODE_ENV=development

  prod:
    init: true
    container_name: histvv2025-prod
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - nw
    restart: always

networks:
  nw:
    driver: bridge
    attachable: false

