services:
  prod:
    init: true
    container_name: histvv2025-prod
    build: 
      context: .
      args:
        SITE_URL: http://localhost
#    environment:
#      - HTTPS_PROXY=http://zoneproxy.zi.uzh.ch:8080
#      - HTTP_PROXY=http://zoneproxy.zi.uzh.ch:8080
#      - NO_PROXY=localhost,127.0.0.1
    ports:
      - "80:80"  
    networks:
      - nw
    restart: always

networks:
  nw:
    driver: bridge
    attachable: false

