networks:
  histvv-nw:

services:
  prod:
    init: true
    container_name: histvv2025
    build:
      context: .
      args:
        SITE_URL: http://localhost
    environment:
      HOST: "0.0.0.0"
      PORT: "3001"  # Prozess lauscht in Container auf 3001
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL:-https://www.zi.uzh.ch/cgi-bin/esproxy/archiv_proxy_test.py}
    ports:
      - "80:3001"
    networks: [histvv-nw]
    volumes:
      - ./data:/app/data:ro
    restart: unless-stopped
