networks:
  histvv-nw:

services:
  prod:
    init: true
    container_name: histvv
    build:
      context: .
      args:
        SITE_URL: http://localhost
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL:-https://ziwwwsearchtest01.uzh.ch:9200}
      HISTVV_INDEX: ${HISTVV_INDEX:-uzh_archiv_histvv}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-uzh_archiv_admin}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    ports:
      - "80:80"
    networks: [histvv-nw]
    restart: always
    depends_on:
      indexer:
        condition: service_completed_successfully  # ⬅️ warte bis Indexer fertig ist
  indexer:
    image: node:20-alpine
    container_name: histvv2025-indexer
    working_dir: /app
    volumes:
      - .:/app:ro
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL:-https://ziwwwsearchtest01.uzh.ch:9200}
      HISTVV_INDEX: ${HISTVV_INDEX:-uzh_archiv_histvv}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME:-uzh_archiv_admin}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      DATA_VERANST: ${DATA_VERANST:-data/tbl_veranstaltungen-merged.json}
      DATA_DOZ: ${DATA_DOZ:-data/tbl_dozenten.json}
      # Hard Drop+Recreate:
      # FORCE_REINDEX: "1"
    command: ["node","scripts/index-elasticsearch.mjs"]
    networks: [histvv-nw]
    restart: "no"
