services:
  prod:
    init: true
    container_name: histvv2025-prod
    build: 
      context: .
      args:
        SITE_URL: http://localhost
    ports:
      - "80:80"  
    networks:
      - nw
    restart: always

networks:
  nw:
    driver: bridge
    attachable: false

